[transactions]

prefer_labels = true # have labels override categories

# Vendors to ignore
ignore_vendors = [
    "COSTCO GAS #1234"
]

# Accounts to ignore
ignore_accounts = [
    "Chase Saving 0123",
    "Robinhood Investments",
]

# Categories to ignore
ignore_categories = [
    "Credit Card Payment",
    "Transfer",
]
